# Generated by Django 5.0.6 on 2024-06-08 17:52

import autoslug.fields
import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PsychologyField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discipline_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=1500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_identifier", models.URLField(unique=True)),
                ("title", models.CharField()),
                ("year", models.IntegerField(blank=True, null=True)),
                ("outlet", models.CharField(blank=True, null=True)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("issue", models.IntegerField(blank=True, null=True)),
                ("pages", models.CharField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("authors", models.ManyToManyField(to="psychology_models.author")),
            ],
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=1500, null=True),
                ),
                ("explanation", markdownx.models.MarkdownxField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="psychology_models.framework",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="psychology_models.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwarePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=1500, null=True),
                ),
                ("documentation", models.URLField(blank=True, null=True)),
                ("code_repository_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="psychology_models.programminglanguage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField(max_length=3000)),
                ("explanation", markdownx.models.MarkdownxField(null=True)),
                ("code_repository_url", models.URLField(blank=True, null=True)),
                ("data_url", models.URLField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("framework", models.ManyToManyField(to="psychology_models.framework")),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="psychology_models.programminglanguage",
                    ),
                ),
                (
                    "psychology_field",
                    models.ManyToManyField(
                        blank=True, to="psychology_models.psychologyfield"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitting_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="psychology_models.publication",
                    ),
                ),
                (
                    "software_package",
                    models.ManyToManyField(
                        blank=True, to="psychology_models.softwarepackage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=200, null=True)),
                (
                    "additional_details",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="psychology_models.publication",
                    ),
                ),
                (
                    "variables",
                    models.ManyToManyField(blank=True, to="psychology_models.variable"),
                ),
            ],
        ),
    ]
