# Generated by Django 5.0.6 on 2024-05-29 12:15

import autoslug.fields
import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Behaviour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField()),
                ("language_documentation", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Measurementinstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_name", models.CharField(max_length=200)),
                ("instrument_description", models.TextField(max_length=200, null=True)),
                (
                    "additional_details",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Model", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                (
                    "publication",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Psychfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discipline_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_name", models.CharField(max_length=200)),
                ("variable_description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("framework_name", models.CharField()),
                (
                    "framework_description",
                    models.TextField(blank=True, max_length=1500, null=True),
                ),
                ("explanation", markdownx.models.MarkdownxField(blank=True, null=True)),
                (
                    "parent_framework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="psychology_models.framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychologyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField(max_length=3000)),
                ("explanation", markdownx.models.MarkdownxField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("codeURL", models.URLField(blank=True, max_length=254, null=True)),
                ("dataURL", models.URLField(blank=True, max_length=254, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
                ("framework", models.ManyToManyField(to="psychology_models.framework")),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psychology_models.language",
                    ),
                ),
                (
                    "psychfield",
                    models.ManyToManyField(
                        blank=True, to="psychology_models.psychfield"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitting_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modelvariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("details", models.TextField(blank=True, max_length=1500, null=True)),
                (
                    "measurementinstrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="psychology_models.measurementinstrument",
                    ),
                ),
                (
                    "modelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelvariables",
                        to="psychology_models.psychologymodel",
                    ),
                ),
                (
                    "variableId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psychology_models.variable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_identifier", models.URLField(unique=True)),
                ("title", models.CharField()),
                ("year", models.IntegerField(null=True)),
                ("outlet", models.CharField(blank=True, null=True)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("issue", models.IntegerField(blank=True, null=True)),
                ("pages", models.CharField(blank=True, null=True)),
                ("authors", models.ManyToManyField(to="psychology_models.author")),
            ],
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="psychology_models.publication",
            ),
        ),
        migrations.AddField(
            model_name="measurementinstrument",
            name="instrument_publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="psychology_models.publication",
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="psychology_models.publication",
            ),
        ),
        migrations.CreateModel(
            name="Softwarepackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=1500, null=True),
                ),
                ("documentation", models.URLField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psychology_models.language",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="softwarepackage",
            field=models.ManyToManyField(
                blank=True, to="psychology_models.softwarepackage"
            ),
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="model_variables",
            field=models.ManyToManyField(
                blank=True,
                through="psychology_models.Modelvariable",
                to="psychology_models.variable",
            ),
        ),
        migrations.AddField(
            model_name="measurementinstrument",
            name="variables",
            field=models.ManyToManyField(blank=True, to="psychology_models.variable"),
        ),
    ]
