# Generated by Django 5.0.6 on 2024-06-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="unique_identifier",
        ),
        migrations.AddField(
            model_name="author",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="framework",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="programminglanguage",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="psychologyfield",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="url",
            field=models.URLField(default="http://example.com/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="softwarepackage",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="variable",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="ModelVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1500, null=True)),
                ("reference", models.CharField(max_length=12, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="Variables",
                        to="psychology_models.psychologymodel",
                    ),
                ),
                (
                    "variable_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="psychology_models.variable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="model_variable",
            field=models.ManyToManyField(
                blank=True,
                through="psychology_models.ModelVariable",
                to="psychology_models.variable",
            ),
        ),
        migrations.DeleteModel(
            name="MeasurementInstrument",
        ),
    ]
