# Generated by Django 5.0.6 on 2024-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0002_remove_publication_unique_identifier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="softwarepackage",
            old_name="documentation",
            new_name="documentation_url",
        ),
    ]
