# Generated by Django 5.0.6 on 2024-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "psychology_models",
            "0003_rename_documentation_softwarepackage_documentation_url",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="psychologymodel",
            name="publication",
        ),
        migrations.RemoveField(
            model_name="framework",
            name="publication",
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="publication_csl_fetched_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="publication_csl_json",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="publication_doi",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="psychologyfield",
            name="discipline_name",
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
    ]
