# Generated by Django 5.0.6 on 2024-07-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0004_remove_publication_authors_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PsychologyField",
            new_name="PsychologyDiscipline",
        ),
        migrations.RenameField(
            model_name="psychologymodel",
            old_name="psychology_field",
            new_name="psychology_discipline",
        ),
    ]
