# Generated by Django 5.0.6 on 2024-07-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0006_rename_discipline_name_psychologydiscipline_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologymodel",
            name="publication_citation",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="publication_citation_fetched_at",
            field=models.DateTimeField(null=True),
        ),
    ]
