# Generated by Django 5.0.7 on 2024-07-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0007_psychologymodel_publication_citation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelvariable",
            name="reference",
        ),
        migrations.AddField(
            model_name="framework",
            name="publication_citation",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="framework",
            name="publication_citation_fetched_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="framework",
            name="publication_csl_fetched_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="framework",
            name="publication_csl_json",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="framework",
            name="publication_doi",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="modelvariable",
            name="name",
            field=models.CharField(default="name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="framework",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modelvariable",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programminglanguage",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologydiscipline",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologymodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="softwarepackage",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variable",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
