# Generated by Django 5.0.7 on 2024-07-11 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0008_remove_modelvariable_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psychologymodel",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="psychologymodel",
            name="submitting_user",
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="review_user",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="psychologymodel",
            name="submit_user",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submit_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="publication_citation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="publication_citation_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="publication_csl_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="publication_csl_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="framework",
            name="publication_doi",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologymodel",
            name="publication_citation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologymodel",
            name="publication_citation_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologymodel",
            name="publication_csl_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologymodel",
            name="publication_csl_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologymodel",
            name="publication_doi",
            field=models.CharField(blank=True, null=True),
        ),
    ]
