# Generated by Django 5.0.7 on 2024-07-11 19:58

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0012_alter_psychologydiscipline_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologydiscipline",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="psychology_discipline_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
