# Generated by Django 5.0.7 on 2024-08-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0015_rename_model_id_modelvariable_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelvariable",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="model_variables",
                to="psychology_models.psychologymodel",
            ),
        ),
    ]
