# Generated by Django 5.0.8 on 2024-08-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0016_alter_modelvariable_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelvariable",
            name="model",
        ),
        migrations.RemoveField(
            model_name="psychologymodel",
            name="model_variable",
        ),
        migrations.AlterField(
            model_name="modelvariable",
            name="variable",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="psychology_models.variable",
            ),
            preserve_default=False,
        ),
    ]
