# Generated by Django 5.0.8 on 2024-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0017_remove_modelvariable_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologymodel",
            name="model_variable",
            field=models.ManyToManyField(
                blank=True, to="psychology_models.modelvariable"
            ),
        ),
    ]
