# Generated by Django 5.0.8 on 2024-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0019_alter_psychologymodel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="documentation_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
