# Generated by Django 5.0.8 on 2024-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0020_framework_documentation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologymodel",
            name="submission_remarks",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
