# Generated by Django 5.0.8 on 2024-08-29 17:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psychology_models", "0022_framework_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framework",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
