alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - cluster_name: psychomodels-production
    db_name: defaultdb
    db_user: doadmin
    engine: PG
    name: psychomodels-production
    production: true
    version: "16"
domains:
  - domain: psychomodels.org
    type: PRIMARY
  - domain: www.psychomodels.com
    type: ALIAS
  - domain: psychomodels.net
    type: ALIAS
    zone: psychomodels.org
  - domain: www.psychomodels.org
    type: ALIAS
    zone: psychomodels.org
  - domain: psychomodels.com
    type: ALIAS
    zone: psychomodels.com
  - domain: www.psychomodels.net
    type: ALIAS
    zone: psychomodels.net
envs:
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:RvzKrXfj9f4ehLeyNJ2eLDgjHfopHU7P:iJqgECGHsKVpoU9lWS0NzdKqdC1aZVGoc0cB5Xg2+QvvLH4+ynCkhLVz+d/0zo551yX3QLK6pw==]
  - key: DEBUG_LOGGING
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: SENTRY_DSN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:kQkpA0xS/ILnmDsUc1iPYDZ/FpqD7Wtd:TYH7OZSA9Ar7vonZq4KMNTb2uJ5VVGMgPL/QTQyaQZKbZdyVnO2A+zH0ynBBl2xhmHjEi64+N1zKGcL9PE+Fc/gGF8wgp1W1GkQpSnvRu0iypgJItgWQ86aOrijLuyAb3VRo+tDvNY88CK9txukU]
  - key: ALGOLIA_APP_ID
    scope: RUN_AND_BUILD_TIME
    value: UWHM5C7DG6
  - key: ALGOLIA_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:nXVAvdVsI0FXzZn2iAL7rgoBO5gqr+r/:7/hqpSosucxKQYb342vdl1Doq/egbg9EHa08ILup5JrXZ/RizpcGLq6l1Jh0vZ0h]
  - key: VITE_ALGOLIA_PUBLIC_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: 3f4d1eb45e782a43d095f5e1f6fd840c
  - key: VITE_ALGOLIA_APP_ID
    scope: RUN_AND_BUILD_TIME
    value: UWHM5C7DG6
  - key: GOOGLE_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: 1000864224746-mvnhaumfkrvfp4s13aufu7fsngqrf47g.apps.googleusercontent.com
  - key: GITHUB_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: Ov23lipaWwlxIGwe31ft
  - key: ORCID_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: APP-G86Q0EWO1JJT6IR0
  - key: SENTRY_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: GOOGLE_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: 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
  - key: EMAIL_HOST
    scope: RUN_AND_BUILD_TIME
    value: smtp.mailgun.org
  - key: EMAIL_HOST_USER
    scope: RUN_AND_BUILD_TIME
    value: postmaster@mail.psychomodels.org
  - key: EMAIL_HOST_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:jrFPIGmlyuGTtsCBjxcUJYddD3DEfC54:ECdEmRtmRwgyLWALzQewI15rFS7C627Xka9SLHcq5F8m0T6t0cAZhMADhWNzygOMnLYhYEA39oYMLGHMHCBZqJjg]
  - key: DEFAULT_FROM_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: PsychoModels <no-reply@psychomodels.org>
  - key: ORCID_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: eec7f3aa-0922-4f1d-80e0-cc870566ec3d
  - key: GITHUB_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: f9c5a256b4a1263edebab1cfa16be54cbd268657
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: server
      match:
        path:
          prefix: /
    - component:
        name: static
      match:
        path:
          prefix: /static
jobs:
  - envs:
      - key: DISABLE_COLLECTSTATIC
        scope: BUILD_TIME
        value: "1"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${psychomodels-production.DATABASE_URL}
    github:
      branch: main
      repo: PsychoModels/psychomodels
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    kind: PRE_DEPLOY
    name: migrate
    run_command: DJANGO_VITE_DEV_MODE=True python manage.py migrate
name: psychomodels-production
region: ams
services:
  - build_command: pipenv install --deploy && DJANGO_VITE_DEV_MODE=True yarn run build
      && pipenv run python manage.py collectstatic --noinput
    environment_slug: python
    envs:
      - key: DISABLE_COLLECTSTATIC
        scope: BUILD_TIME
        value: "1"
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_TIME
        value: psychomodels-production-9tw7w.ondigitalocean.app,psychomodels.org,psychomodels.com,psychomodels.net,www.psychomodels.com,www.psychomodels.net,www.psychomodels.org,psychomodels-production-9tw7w.ondigitalocean.app
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${psychomodels-production.DATABASE_URL}
    github:
      branch: main
      repo: PsychoModels/psychomodels
    health_check:
      failure_threshold: 5
      http_path: /health-check/
      initial_delay_seconds: 30
      period_seconds: 10
      port: 8080
      success_threshold: 1
      timeout_seconds: 5
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: server
    run_command: gunicorn --worker-tmp-dir /dev/shm psychomodels.wsgi
    source_dir: /
static_sites:
  - build_command: pipenv install --deploy && DJANGO_VITE_DEV_MODE=True yarn run build
      && pipenv run python manage.py collectstatic --noinput
    environment_slug: python
    github:
      branch: main
      repo: PsychoModels/psychomodels
    name: static
    output_dir: /collectedstatic
    source_dir: /
