# Generated by Django 5.0.8 on 2024-08-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlighted", "0001_initial"),
        ("psychology_models", "0021_psychologymodel_submission_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="HighlightedDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "psychology_discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psychology_models.psychologydiscipline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HighlightedProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psychology_models.programminglanguage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HighlightedPsychologyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "psychology_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="psychology_models.psychologymodel",
                    ),
                ),
            ],
        ),
    ]
