# Generated by Django 5.0.8 on 2024-08-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "highlighted",
            "0002_highlighteddiscipline_highlightedprogramminglanguage_and_more",
        ),
        ("psychology_models", "0021_psychologymodel_submission_remarks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HighlightedDiscipline",
            new_name="HighlightedPsychologyDiscipline",
        ),
    ]
