# Generated by Django 5.0.6 on 2024-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(null=True),
        ),
    ]
