# Generated by Django 5.1.1 on 2024-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_user_country_alter_user_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, null=True),
        ),
    ]
