# Generated by Django 5.1.1 on 2025-02-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
